### ISSUE TITLE
Can't run due to missing Evaluation module

### ISSUE THREAD

**Issue by gavotte25** [smallcube/Class-balanced-Ensemble#1]
Hi,
I'm trying your code and encounter import issue due to missing module Evaluation. It is referred in MyEnsemble.py.
`from Evaluation import acc`.
Could you please provide this file. 
Thank you.

**Comment by smallcube** [comment]
Evaluation.py has been uploaded. Thanks!

**Comment by gavotte25** [comment]
Thank you! It helps a lot.
